### ISSUE TITLE
Feature Request:  Support for Fastly WAF

### ISSUE THREAD

**Issue by marmarama** [sethvargo/go-fastly#35]
Fastly are introducing a cloud WAF service, currently on limited availability.  It would be good for go-fastly to support this.

API docs:  https://docs.fastly.com/api/waf

**Comment by karnauskas** [comment]
👍

**Comment by sethvargo** [comment]
Hi @marmarama @karnauskas 

Most of the discussion is occurring in https://github.com/sethvargo/go-fastly/pull/51. I've been in touch with Fastly and I think we have a path forward, but WAF is in limited availability, so there are some things I need to figure out around sustainable testing, etc.

**Comment by karnauskas** [comment]
Wondering what is future related to all limited availability features on Fasly. Eg we get early access to them but we're unable to configure them using this library (or Terraform which depends on this). Also this library could information how to develop and test against Fastly APIs.

**Comment by sethvargo** [comment]
Hi @karnauskas 

Fastly ultimately makes the decision of whether they want to enable functionality on our testing account so that I can add functionality to this library. I can't add or develop functionality that I cannot test. I've been in touch with them regarding the WAF functionality, and we have a good path forward.

However, WAF is still in limited availability. Even if I completed this functionality today, it wouldn't make it into Terraform until it is GA as per Terraform's policy. You could fork the provider or write your own provider to include those beta features, but it's unlikely they will make it into the official terraform-provider-fastly until they are GA. The same is true for things like imageoptim, etc.
